# Site
name: "Travis Cao"
description: "Econ Ph.D. student at UW-Madison"
logo: 'assets/images/logo.png'
    
# Collections
collections:
  pages: 
    output: true
    permalink: /:categories/:title/

# Other
markdown: kramdown
highlighter: rouge
